### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by void-inject** [waived/vortex-file-binder#1]
Will it work on linux? i mean, it is .exe

**Comment by waived** [comment]
This program is dependent on NET Framework, so no. It will run only on Windows platforms. If I were to have written it in NET Core (which is Linux compatible) then yes. However, if you're looking for a Linux compatible File Binder I wouldn't even bother with this language. This is because Windows uses EXE files, and Linux/Unix will use ELF (Executable and Linkable Format) instead. Languages like C, Cpp, Delphi, and GoLang can either run as an EXE of ELF. I would personally lean towards those.
